"""Initial schema setup with per-repo code_chunks

Revision ID: 3536fc23a636
Revises: 
Create Date: 2026-08-30 01:55:01.780561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3536fc23a636'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('file_sha', sa.String(length=40), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'file_path', 'chunk_index', 'file_sha', name='uq_repo_file_chunk_sha')
    )
    op.create_index('code_chunks_embedding_hnsw_idx', 'code_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 128}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_code_chunks_file_sha'), 'code_chunks', ['file_sha'], unique=False)
    op.create_index(op.f('ix_code_chunks_repo_name'), 'code_chunks', ['repo_name'], unique=False)
    op.create_index('ix_code_chunks_repo_path', 'code_chunks', ['repo_name', 'file_path'], unique=False)
    op.create_table('prs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('github_pr_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prs_github_pr_id'), 'prs', ['github_pr_id'], unique=True)
    op.create_index(op.f('ix_prs_repo_name'), 'prs', ['repo_name'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pr_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['prs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('agent_events_created_at_brin_idx', 'agent_events', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_agent_events_pr_created', 'agent_events', ['pr_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_events_pr_id'), 'agent_events', ['pr_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pr_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['prs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_pr_id'), 'findings', ['pr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_pr_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_agent_events_pr_id'), table_name='agent_events')
    op.drop_index('ix_agent_events_pr_created', table_name='agent_events')
    op.drop_index('agent_events_created_at_brin_idx', table_name='agent_events', postgresql_using='brin')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_prs_repo_name'), table_name='prs')
    op.drop_index(op.f('ix_prs_github_pr_id'), table_name='prs')
    op.drop_table('prs')
    op.drop_index('ix_code_chunks_repo_path', table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_repo_name'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_sha'), table_name='code_chunks')
    op.drop_index('code_chunks_embedding_hnsw_idx', table_name='code_chunks', postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 128}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
