"""add source column to code_chunks

Revision ID: ba7bbdfe8a95
Revises: 3536fc23a636
Create Date: 2026-09-08 09:19:07.816078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7bbdfe8a95'
down_revision: Union[str, Sequence[str], None] = '3536fc23a636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing chunks need a source value before the column can be required.
    op.add_column('code_chunks', sa.Column('source', sa.String(length=20), nullable=True))
    op.execute("UPDATE code_chunks SET source = 'pr_diff' WHERE source IS NULL")
    op.alter_column('code_chunks', 'source', existing_type=sa.String(length=20), nullable=False)
    op.drop_constraint(op.f('uq_repo_file_chunk_sha'), 'code_chunks', type_='unique')
    op.create_unique_constraint('uq_repo_file_source_chunk_sha', 'code_chunks', ['repo_name', 'file_path', 'source', 'chunk_index', 'file_sha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repo_file_source_chunk_sha', 'code_chunks', type_='unique')
    op.create_unique_constraint(op.f('uq_repo_file_chunk_sha'), 'code_chunks', ['repo_name', 'file_path', 'chunk_index', 'file_sha'], postgresql_nulls_not_distinct=False)
    op.drop_column('code_chunks', 'source')
    # ### end Alembic commands ###
